import {StyleSheet} from 'react-native';

import theme from '@/src/Global/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.COLORS.BACKGROUND_ELEVATED,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    marginTop: 8,
    marginBottom: 20,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 16,
    color: theme.COLORS.TEXT_CONTRAST,
    textAlign: 'left',
  },
  headerSpacer: {
    width: 36,
  },
  statusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  inputSpacing: {
    marginBottom: 10,
  },
  statusItem: {
    width: '50%',
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  addButton: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FAFAFA',
    borderRadius: 20,
    paddingVertical: 10,
  },
  addButtonText: {
    marginLeft: 8,
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.PURPLE_BASE,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  summaryLabel: {
    fontFamily: theme.FONT_FAMILY.REGULAR,
    fontSize: 13,
    color: theme.COLORS.TEXT_MUTED,
  },
  summaryMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryMetaText: {
    marginRight: 12,
    fontFamily: theme.FONT_FAMILY.REGULAR,
    fontSize: 12,
    color: theme.COLORS.TEXT_MUTED,
  },
  summaryValue: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 13,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  discountLabel: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  discountBadge: {
    marginLeft: 8,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: theme.COLORS.GRAY_200,
  },
  discountBadgeText: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 12,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  summaryValueDanger: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 13,
    color: theme.COLORS.DANGER_BASE,
  },
  totalRow: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: theme.COLORS.BORDER_PRIMARY,
    paddingTop: 12,
  },
  totalLabel: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 13,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  totalValue: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 16,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  footer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: theme.COLORS.BORDER_PRIMARY,
    backgroundColor: theme.COLORS.BACKGROUND_ELEVATED,
  },
  secondaryButton: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  secondaryButtonText: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.TEXT_MUTED,
  },
  primaryButton: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.COLORS.PURPLE_BASE,
  },
  primaryButtonText: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.BACKGROUND_ELEVATED,
  },
  sheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  sheetContainer: {
    backgroundColor: theme.COLORS.BACKGROUND_ELEVATED,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sheetTitle: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 16,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  sheetInput: {
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: theme.FONT_FAMILY.REGULAR,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
    marginBottom: 12,
  },
  sheetTextarea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  sheetMoneyField: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flex: 1,
    marginRight: 12,
  },
  sheetCurrency: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
    marginRight: 6,
  },
  sheetMoneyInput: {
    flex: 1,
    fontFamily: theme.FONT_FAMILY.REGULAR,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  sheetQtyField: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  sheetQtyButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.COLORS.PURPLE_LIGHT,
  },
  sheetQtyText: {
    width: 28,
    textAlign: 'center',
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  sheetActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  sheetDeleteButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: theme.COLORS.BACKGROUND_ELEVATED,
  },
  sheetSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    paddingHorizontal: 20,
    borderRadius: 24,
    backgroundColor: theme.COLORS.PURPLE_BASE,
  },
  sheetSaveButtonText: {
    marginLeft: 8,
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.BACKGROUND_ELEVATED,
  },
});
