import {StyleSheet} from 'react-native';

import theme from '@/src/Global/theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.50)',
  },
  sheetContainer: {
    maxHeight: '85%',
    backgroundColor: theme.COLORS.BACKGROUND_ELEVATED,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  scrollView: {
    flexGrow: 0,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  title: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 16,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: theme.FONT_FAMILY.REGULAR,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
    marginBottom: 12,
  },
  textarea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  moneyField: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flex: 1,
    marginRight: 12,
  },
  currency: {
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
    marginRight: 6,
  },
  moneyInput: {
    flex: 1,
    fontFamily: theme.FONT_FAMILY.REGULAR,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  qtyField: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  qtyButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.COLORS.PURPLE_LIGHT,
  },
  qtyText: {
    width: 28,
    textAlign: 'center',
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.TEXT_CONTRAST,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  deleteButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.COLORS.BORDER_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: theme.COLORS.BACKGROUND_ELEVATED,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    paddingHorizontal: 20,
    borderRadius: 24,
    backgroundColor: theme.COLORS.PURPLE_BASE,
  },
  saveButtonText: {
    marginLeft: 8,
    fontFamily: theme.FONT_FAMILY.SEMIBOLD,
    fontSize: 14,
    color: theme.COLORS.BACKGROUND_ELEVATED,
  },
});
